# Generated by Django 4.2 on 2026-04-26 03:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_remove_landparcel_geometry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landparcel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='landparcel',
            name='longitude',
        ),
        migrations.AddField(
            model_name='landparcel',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
