# Generated by Django 4.2 on 2026-04-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0003_remove_landparcel_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='employee_id',
            new_name='officer_id',
        ),
        migrations.AddField(
            model_name='officer',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='officer',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
